config/routes.rb
Rails.application.routes.draw do
  get "password_resets/new"
  get "password_resets/edit"
  namespace :admin do
      resources :hotels
      resources :day_price_adjustments
      resources :bookings do
        member do
          patch :toggle_status
        end
      end
      resources :users do
        member do
          patch :toggle_admin
        end
      end
  end

  resources :bookings do
    collection do
      post :calculate_price
    end
    member do
      patch :cancel
    end
  end
  resources :hotels do
    member do
      post :room_price
    end
    resources :reviews
  end
  resources :users, only: [ :show, :edit, :update, :create ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "home#index"

  get "admin", to: "admin#index", as: "admin"

  get "signup" => "users#new"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  resources :account_activations, only: [ :edit ]
  resources :password_resets, only: [ :new, :create, :edit, :update ]
end

app/models/booking.rb
class Booking < ApplicationRecord
  include PricingHelper
  belongs_to :user
  belongs_to :hotel

  enum status: {
    confirmed: "confirmed",
    cancelled: "cancelled"
  }

  enum room_type: {
    single_room: "single_room",
    double_room: "double_room",
    suite: "suite"
  }

  validates :start_date, :end_date, presence: true
  validate :dates_are_valid
  validate :no_double_booking
  validates :room_type, presence: true
  validates :total_cost, presence: true
  validates :booked_name, :booked_number, presence: true

  before_validation :set_total_cost

  def send_booking_email
    UserMailer.booking_confirmation(self).deliver_now
  end

  private

  def dates_are_valid
    if start_date && !start_date.is_a?(Date)
      errors.add(:start_date, "must be a valid date")
    end

    if end_date && !end_date.is_a?(Date)
      errors.add(:end_date, "must be a valid date")
    end

    if start_date && start_date < Date.today
      errors.add(:start_date, "cannot be in the past")
    end

    if start_date && end_date && end_date < start_date
      errors.add(:end_date, "must be equal to or after start date")
    end
  end

  def no_double_booking
    conflicting_booking = Booking.where(hotel_id: hotel_id, room_type: room_type)
                                 .where("start_date <= ? AND end_date >= ?", end_date, start_date)
                                 .where.not(id: id) # Exclude current booking from the check if updating
                                 .where(status: "confirmed") # Consider only confirmed bookings

    if conflicting_booking.exists?
      conflicting_dates = conflicting_booking.pluck(:start_date, :end_date).map { |sd, ed| "#{sd} to #{ed}" }.join(", ")
      errors.add(:base, "Room is already booked for the following confirmed dates: #{conflicting_dates}.")
    end
  end

  def set_total_cost
    self.total_cost = PricingHelper.calculate_total_cost(start_date, end_date, PricingHelper.room_price_for_type(hotel, room_type), hotel) if start_date && end_date && PricingHelper.room_price_for_type(hotel, room_type)
  end
end

app/controllers/admin/bookings_controller.rb
class Admin::BookingsController < AdminController
    before_action :set_booking, only: [ :show, :toggle_status, :destroy ]

  def index
    @admin_bookings = Booking.all

    if params[:id].present?
      @admin_bookings = Booking.where(id: params[:id])
    end

    if params[:start_date].present? && params[:end_date].present?
      start_date = Date.parse(params[:start_date])
      end_date = Date.parse(params[:end_date])

      if start_date > end_date
        flash[:error] = "Start date cannot be after end date."
        redirect_to admin_bookings_path
      end

      @admin_bookings = @admin_bookings.where(start_date: start_date.beginning_of_day..end_date.end_of_day)
    elsif params[:start_date].present?
      start_date = Date.parse(params[:start_date])
      @admin_bookings = @admin_bookings.where("start_date >= ?", start_date.beginning_of_day)
    elsif params[:end_date].present?
      end_date = Date.parse(params[:end_date])
      @admin_bookings = @admin_bookings.where("end_date <= ?", end_date.end_of_day)
    end

    # Handle user_id and hotel_id filtering
    @admin_bookings = @admin_bookings.where(user_id: params[:user_id]) if params[:user_id].present?
    @admin_bookings = @admin_bookings.where(hotel_id: params[:hotel_id]) if params[:hotel_id].present?

    if params[:status].present?
      @admin_bookings = @admin_bookings.where(status: params[:status])
    end

    if params[:order] == "user_id_asc"
      @admin_bookings = @admin_bookings.order(user_id: :asc)
    elsif params[:order] == "user_id_desc"
      @admin_bookings = @admin_bookings.order(user_id: :desc)
    elsif params[:order] == "id_asc"
      @admin_bookings = @admin_bookings.order(id: :asc)
    elsif params[:order] == "id_desc"
      @admin_bookings = @admin_bookings.order(id: :desc)
    elsif params[:order] == "hotel_id_asc"
      @admin_bookings = @admin_bookings.order(hotel_id: :asc)
    elsif params[:order] == "hotel_id_desc"
      @admin_bookings = @admin_bookings.order(hotel_id: :desc)
    else
      @admin_bookings = @admin_bookings.order(id: :asc)
    end

    @admin_bookings = @admin_bookings.paginate(page: params[:page], per_page: 10)
  end

  def show
  end

  def toggle_status
    new_status = @admin_booking.status == "confirmed" ? "cancelled" : "confirmed"
    if @admin_booking.update(status: new_status)
      redirect_back fallback_location: admin_booking_path(@admin_booking), notice: "Booking status was successfully updated."
    else
      redirect_to admin_booking_path(@admin_booking), alert: "Failed to update booking status."
    end
  end


  def destroy
    @admin_booking.destroy
    redirect_to admin_bookings_path, notice: "Booking was successfully destroyed."
  end

  private

  def set_booking
    @admin_booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:id, :start_date, :end_date, :room_type, :room_price, :total_cost, :hotel_id, :user_id, :status)
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_hotel_and_current_user, only: [ :new, :create, :calculate_price ]
  before_action :logged_in_user, only: [ :index, :show, :new, :create, :destroy, :update, :cancel ]
  before_action :set_booking, only: %i[ show edit update destroy cancel ]
  before_action :correct_user, only: [ :cancel, :edit, :destroy ]

  # GET /bookings or /bookings.json
  def index
    @bookings = current_user.bookings

    if params[:filter].present?
      case params[:filter]
      when "confirmed"
        @bookings = @bookings.where(status: "confirmed")
      when "cancelled"
        @bookings = @bookings.where(status: "cancelled")
      end
    end

    @bookings = @bookings.paginate(page: params[:page], per_page: 5)
  end

  # GET /bookings/1 or /bookings/1.json
  def show
  end

  # GET /bookings/new

  def new
    @booking = Booking.new
    if params[:hotel_id].present?
      @hotel = Hotel.find_by(id: params[:hotel_id])
      if @hotel.nil?
        redirect_to hotels_path
        return
      end
    else
      redirect_to hotels_path
      return
    end

    @booking.booked_name = "#{current_user.first_name} #{current_user.last_name}"
    @booking.booked_number = current_user.mobile_number # Adjust based on your actual attribute name
  end


  # POST /bookings/cancel/1
  def cancel
    if @booking.update(status: "cancelled")
      redirect_to booking_path(@booking)
    else
      redirect_to booking_path(@booking)
    end
  end

  # GET /bookings/1/edit
  def edit
  end

  def calculate_price
    start_date = Date.parse(params[:start_date])
    end_date = Date.parse(params[:end_date])
    room_type = params[:room_type]
    hotel = Hotel.find(params[:hotel_id])

    room_price = PricingHelper.room_price_for_type(hotel, room_type)
    total_cost = PricingHelper.calculate_total_cost(start_date, end_date, room_price, hotel)

    render json: { total_cost: total_cost }
  rescue => e
    render json: { error: e.message }, status: :unprocessable_entity
  end

def create
  @booking = Booking.new(booking_params)
  @booking.user_id = current_user.id
  @booking.start_date = params[:start_date]
  @booking.end_date = params[:end_date]
  @booking.booked_name = "#{current_user.first_name} #{current_user.last_name}"
  @booking.booked_number = current_user.mobile_number # Adjust based on your actual attribute name

  respond_to do |format|
    if @booking.save
      @booking.send_booking_email
      format.html { redirect_to booking_url(@booking) }
      format.json { render :show, status: :created, location: @booking }
    else
      # Reload @hotel and set booked_name and booked_number again
      @hotel = Hotel.find_by(id: params[:booking][:hotel_id])
      @booking.booked_name = "#{current_user.first_name} #{current_user.last_name}"
      @booking.booked_number = current_user.mobile_number # Adjust based on your actual attribute name
      format.html { render :new, status: :unprocessable_entity }
      format.json { render json: @booking.errors, status: :unprocessable_entity }
    end
  end
end


  # PATCH/PUT /bookings/1 or /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to booking_url(@booking), notice: "Booking was successfully updated." }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1 or /bookings/1.json
  def destroy
    @booking.destroy!

    respond_to do |format|
      format.html { redirect_to bookings_url, notice: "Booking was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    def set_hotel_and_current_user
      @current_user = current_user
    end

    # Only allow a list of trusted parameters through.
    def booking_params
      params.require(:booking).permit(:id, :start_date, :end_date, :room_type, :room_price, :total_cost, :hotel_id, :user_id, :status)
    end

    def correct_user
      @booking = current_user.bookings.find_by(id: params[:id])
      if @booking.nil?
        puts "Redirecting to root_url because booking with ID #{params[:id]} does not belong to current user."
        redirect_to root_url
      else
        puts "Booking found: #{@booking.attributes}"
      end
    end

end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/admin/bookings/_booking.html.erb
<div id="<%= dom_id booking %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Start Date:</strong>
    <%= booking.start_date %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">End Date:</strong>
    <%= booking.end_date %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Room Type:</strong>
    <%= booking.room_type.titleize %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Total Cost:</strong>
    <%= booking.total_cost %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Status:</strong>
    <%= booking.status.capitalize %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this booking", [:admin, booking], class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this booking", edit_admin_booking_path(booking), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>

</div>

app/views/admin/bookings/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>
    <h1 class="font-bold text-4xl">Bookings</h1>
    <div class="flex justify-between items-center">
      
      <div class="flex justify-between mb-4 mt-4">
        <%= form_with(url: admin_bookings_path, method: :get, local: true, class: "flex gap-4") do |form| %>
          <div>
          <%= form.label :id, "ID", class: "block text-sm font-medium text-gray-700" %>
          <%= form.number_field :id, value: params[:id], class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm", id: "search-id", min: 1 %>
        </div>
         <div>
            <%= form.label :user_id, "Customer ID", class: "block text-sm font-medium text-gray-700" %>
            <%= form.number_field :user_id, value: params[:user_id], class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm", min: 1 %>
          </div>
          <div>
            <%= form.label :hotel_id, "Hotel ID", class: "block text-sm font-medium text-gray-700" %>
            <%= form.number_field :hotel_id, value: params[:hotel_id], class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm", min: 1 %>
          </div>
          <div>
            <%= form.label :start_date, "Start Date", class: "block text-sm font-medium text-gray-700" %>
            <%= form.date_field :start_date, value: params[:start_date], class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm" %>
          </div>
          <div>
            <%= form.label :end_date, "End Date", class: "block text-sm font-medium text-gray-700" %>
            <%= form.date_field :end_date, value: params[:end_date], class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm" %>
          </div>
          <div>
          <%= form.label :status, "Status", class: "block text-sm font-medium text-gray-700" %>
          <%= form.select :status, [['Confirmed', 'confirmed'], ['Cancelled', 'cancelled']], { prompt: 'Select Status' }, { class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm" } do %>
          <% if params[:status] == 'confirmed' %>
            <option value="confirmed" selected="selected">Confirmed</option>
            <option value="cancelled">Cancelled</option>
          <% elsif params[:status] == 'cancelled' %>
            <option value="confirmed">Confirmed</option>
            <option value="cancelled" selected="selected">Cancelled</option>
          <% else %>
            <option value="confirmed">Confirmed</option>
            <option value="cancelled">Cancelled</option>
          <% end %>
          <% end %>
          </div>
          <div class="flex items-end gap-1">
            <%= form.submit "Filter", class: "inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm hover:sky-100 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500 cursor-pointer", style: "background-color: #3b606f; color: #e4ebe8;" %>
            <% if params[:id].present? || params[:start_date].present? || params[:end_date].present? || params[:user_id].present? || params[:hotel_id].present? || params[:status] %>
              <%= link_to "Clear", admin_bookings_path, class: "inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500 cursor-pointer", style: "background-color: #e4ebe8; color: #3b606f;" %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>


  <div class="flex flex-col w-full overlow-x-auto sm:mx-0.5 lg:mx-0.5">
    <div class="py-2 inline-block min-w-full">
      <div class="overlow-x-auto">
        <table class="min-w-full table-fixed overflow-x-scroll">
          <thead class="bg-white border-b">
            <tr>
              <th scope="col" class="w-1/6 text-sm font-medium text-gray-800 px-6 py-4 text-left">
                <%= link_to url_for(params.permit(:page).merge(order: params[:order] == 'id_asc' || params[:order].blank? ? 'id_desc' : 'id_asc')), class: "flex items-center justify-between" do %>
                  <span>ID</span>
                  <% if params[:order] == 'id_asc' || params[:order].blank? %>
                    <i class="fas fa-arrow-down text-sm text-gray-500"></i>
                  <% else %>
                    <i class="fas fa-arrow-up text-sm text-gray-500"></i>
                  <% end %>
                <% end %>
              </th>
              <th scope="col" class="w-1/6 text-sm font-medium text-gray-800 px-6 py-4 text-left">
                <%= link_to url_for(params.permit(:page).merge(order: params[:order] == 'user_id_asc' || params[:order].blank? ? 'user_id_desc' : 'user_id_asc')), class: "flex items-center justify-between" do %>
                  <span>User ID</span>
                  <% if params[:order] == 'user_id_asc' || params[:order].blank? %>
                    <i class="fas fa-arrow-down text-sm text-gray-500"></i>
                  <% else %>
                    <i class="fas fa-arrow-up text-sm text-gray-500"></i>
                  <% end %>
                <% end %>
              </th>
              <th scope="col" class="w-1/6 text-sm font-medium text-gray-800 px-6 py-4 text-left">
                <%= link_to url_for(params.permit(:page).merge(order: params[:order] == 'hotel_id_asc' || params[:order].blank? ? 'hotel_id_desc' : 'hotel_id_asc')), class: "flex items-center justify-between" do %>
                  <span>Hotel ID</span>
                  <% if params[:order] == 'hotel_id_asc' || params[:order].blank? %>
                    <i class="fas fa-arrow-down text-sm text-gray-500"></i>
                  <% else %>
                    <i class="fas fa-arrow-up text-sm text-gray-500"></i>
                  <% end %>
                <% end %>
              </th>
              <th scope="col" class="w-1/4 text-sm font-medium text-gray-800 px-6 py-4 text-left">Start Date</th>
              <th scope="col" class="w-1/4 text-sm font-medium text-gray-800 px-6 py-4 text-left">End Date</th>
              <th scope="col" class="w-1/4 text-sm font-medium text-gray-800 px-6 py-4 text-left">Status</th>
              <th scope="col" class="w-1/4 text-sm font-medium text-gray-800 px-6 py-4 text-left">Actions</th>
            </tr>
          </thead>
          <tbody>
            <% @admin_bookings.each do |booking| %>
              <tr class="bg-gray-50 border-b cursor-pointer" data-url="<%= admin_booking_path(booking) %>">
                <td class="px-6 py-4 text-sm font-medium text-gray-800"><%= booking.id %></td>
                <td class="px-6 py-4 text-sm font-medium text-gray-800 underline">
                  <%= link_to booking.user_id, admin_user_path(booking.user_id) %>
                </td>
                <td class="px-6 py-4 text-sm font-medium text-gray-800 underline">
                  <%= link_to booking.hotel_id, admin_hotel_path(booking.hotel_id) %>
                </td>
                <td class="px-6 py-4 text-sm font-medium text-gray-800"><%= booking.start_date %></td>
                <td class="px-6 py-4 text-sm font-medium text-gray-800"><%= booking.end_date %></td>
                <td class="px-6 py-4 text-sm font-medium text-gray-800"><%= booking.status.capitalize %></td>
                <td class="px-6 py-4 text-sm font-medium text-gray-800 relative">
                  <div class="flex justify-center items-center">
                    <div class= "flex flex-col">
                    <button class="rounded-full focus:outline-none focus:ring-0 focus:ring-blue-500 flex items-center mt-2" id="options-menu-<%= booking.id %>" aria-haspopup="true" aria-expanded="false">
                      <svg class="h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                        <path fill-rule="evenodd" d="M10 6a2 2 0 100-4 2 2 0 000 4zM2 6a2 2 0 100-4 2 2 0 000 4zm16 0a2 2 0 100-4 2 2 0 000 4z" clip-rule="evenodd" />
                      </svg>
                    </button>

                    <div class="absolute bg-white rounded-lg shadow-lg ring-1 ring-black ring-opacity-5 hidden mt-8 left-4 z-10">
                    <% if booking.status == "confirmed" %>
                      <%= link_to "Cancel", toggle_status_admin_booking_path(booking), method: :patch, class: "block text-center px-4 py-2 text-sm text-gray-700 hover:bg-gray-100", role: "menuitem", data: { turbolinks: false } %>
                    <% elsif booking.status == "cancelled" %>
                      <%= link_to "Reconfirm", toggle_status_admin_booking_path(booking), method: :patch, class: "block text-center px-4 py-2 text-sm text-gray-700 hover:bg-gray-100", role: "menuitem", data: { turbolinks: false } %>
                    <% end %>
                      <%= button_to "Delete", admin_booking_path(booking), method: :delete, data: { confirm: "Are you sure you want to delete this booking?" }, class: "block w-full text-center px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 mt-1", role: "menuitem", data: { turbolinks: false } %>
                    </div>
                    </div>
                  </div>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <div class="pagination flex justify-end mt-4">
      <% if @admin_bookings.total_pages > 1 %>
    <ul class="flex items-center">
      <% if @admin_bookings.current_page > 1 %>
        <li><%= link_to "« Previous", url_for(params.permit!.merge(page: @admin_bookings.current_page - 1)), class: "px-3 py-1 bg-gray-200 text-gray-700 rounded-md mr-2" %></li>
      <% else %>
        <li><span class="px-3 py-1 bg-gray-200 text-gray-400 rounded-md mr-2">« Previous</span></li>
      <% end %>

      <% @admin_bookings.total_pages.times do |page| %>
        <% if @admin_bookings.current_page == page + 1 %>
          <li><span class="px-3 py-1 rounded-md mr-2" style="background-color: #3b606f; color: #e4ebe8;"><%= page + 1 %></span></li>
        <% else %>
          <li><%= link_to page + 1, url_for(params.permit!.merge(page: page + 1)), class: "px-3 py-1 bg-gray-200 text-gray-700 rounded-md mr-2" %></li>
        <% end %>
      <% end %>

      <% if @admin_bookings.current_page < @admin_bookings.total_pages %>
        <li><%= link_to "Next »", url_for(params.permit!.merge(page: @admin_bookings.current_page + 1)), class: "px-3 py-1 bg-gray-200 text-gray-700 rounded-md ml-2" %></li>
      <% else %>
        <li><span class="px-3 py-1 bg-gray-200 text-gray-400 rounded-md ml-2">Next »</span></li>
      <% end %>
    </ul>
  <% end %>
    </div>
  </div>
</div>


<script>
  document.addEventListener("DOMContentLoaded", function() {
    const startDateField = document.getElementById('start-date-field');
    const endDateField = document.getElementById('end-date-field');

    startDateField.addEventListener('change', function() {
      if (startDateField.value > endDateField.value) {
        alert('Start date cannot be after End date.');
        startDateField.value = endDateField.value; // Reset start date to end date
      }
    });

    endDateField.addEventListener('change', function() {
      if (endDateField.value < startDateField.value) {
        alert('End date cannot be before Start date.');
        endDateField.value = startDateField.value; // Reset end date to start date
      }
    });

  });
</script>


<script>
document.addEventListener("DOMContentLoaded", function() {
  const rows = document.querySelectorAll("tr[data-url]");
  const buttons = document.querySelectorAll("[id^='options-menu-']");

  buttons.forEach(button => {
    button.addEventListener("click", function(event) {
      event.stopPropagation(); // Prevents the click event from reaching the row
      const menu = this.nextElementSibling;
      menu.classList.toggle("hidden");
    });
  });

  rows.forEach(row => {
    row.addEventListener("click", function() {
      window.location.href = this.dataset.url;
    });
  });
});

</script>

app/views/admin/bookings/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @admin_booking %>

  <div class="flex justify-between mt-4 my-5">
      <%= link_to "Back to bookings", admin_bookings_path, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      
      <div class="flex ml-4">
        <% if @admin_booking.status == "confirmed" %>
        <%= button_to "Cancel Booking", toggle_status_admin_booking_path(@admin_booking), method: :patch, class: "mr-2 rounded-lg py-3 px-5 inline-block font-medium", style: "background-color: #3b606f; color: #e4ebe8;" %>
        <% elsif @admin_booking.status == "cancelled" %>
           <%= button_to "Reconfirm Booking", toggle_status_admin_booking_path(@admin_booking), method: :patch, class: "mr-2 rounded-lg py-3 px-5 inline-block font-medium", style: "background-color: #3b606f; color: #e4ebe8;" %>
        <% end %>
        <%= button_to "Delete this booking", admin_booking_path(@admin_booking), method: :delete, class: "rounded-lg py-3 px-5 font-medium cursor-pointer", style: "background-color: #e4ebe8; color: #3b606f;" %>
    
      </div>
    </div>

  </div>
</div>