config/routes.rb
Rails.application.routes.draw do
  get "password_resets/new"
  get "password_resets/edit"
  namespace :admin do
      resources :hotels
      resources :day_price_adjustments
      resources :bookings do
        member do
          patch :toggle_status
        end
      end
      resources :users do
        member do
          patch :toggle_admin
        end
      end
  end

  resources :bookings do
    collection do
      post :calculate_price
    end
    member do
      patch :cancel
    end
  end
  resources :hotels do
    member do
      post :room_price
    end
    resources :reviews
  end
  resources :users, only: [ :show, :edit, :update, :create ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "home#index"

  get "admin", to: "admin#index", as: "admin"

  get "signup" => "users#new"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  resources :account_activations, only: [ :edit ]
  resources :password_resets, only: [ :new, :create, :edit, :update ]
end

app/views/shared/_footer.html.erb
<footer class="bg-blue-400 text-white">
  <div class="max-w-6xl mx-auto px-4 py-10 md:py-20">
    <div class="xl:grid xl:grid-cols-3 xl:gap-8">
      <!-- About section -->
      <div class="space-y-8 xl:col-span-1">
        <h3 class="text-sm font-semibold text-gray-200 tracking-wider uppercase">About ChatHotel</h3>
        <p class="text-white leading-6">
          ChatHotel is a premier online booking platform, offering a variety of accommodations to suit every traveler's needs. Our dedication to excellence ensures a memorable and seamless booking experience.
        </p>
      </div>

      <!-- Quick Links -->
      <div class="mt-12 xl:mt-0 xl:col-span-1">
        <h3 class="text-sm font-semibold text-gray-200 tracking-wider uppercase">Quick Links</h3>
        <ul class="mt-4 space-y-4 grid grid-cols-1 sm:grid-cols-2">
          <li><%= link_to "Home", root_path, class: "text-base leading-6 text-white hover:text-gray-100" %></li>
          <!-- Add more links as needed -->
        </ul>
      </div>

      <!-- Contact information -->
      <div class="mt-12 xl:mt-0 xl:col-span-1">
        <h3 class="text-sm font-semibold tracking-wider uppercase text-gray-200">Contact</h3>
        <ul class="mt-4 space-y-4">
          <li>
            <p class="text-base leading-6 text-white">123 Hotel Lane <br>Hotel City, EC 12345</p>
          </li>
          <li>
            <p class="text-base leading-6 text-white">Email: support@chathotel.com</p>
          </li>
          <li>
            <p class="text-base leading-6 text-white">Phone: (123) 456-7890</p>
          </li>
        </ul>
      </div>
    </div>

    <!-- Copyright -->
    <div class="border-t border-gray-700 mt-8 pt-6 md:flex md:items-center md:justify-between">
      <p class="text-base leading-6 text-white md:order-1">
        &copy; <%= Time.now.year %> ChatHotel, Inc. All rights reserved.
      </p>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="sticky top-0 w-full bg-blue-300 z-10 py-4">
  <div class="max-w-7xl mx-auto px-2 sm:px-6 lg:px-8">
    <div class="relative flex items-center justify-between h-16">
      <div class="flex-1 flex items-center justify-center sm:items-stretch sm:justify-between">
        <div class="hidden sm:flex items-center justify-center">
          <div class="flex space-x-10">
            <% if logged_in? %>
              <%= link_to "Logout", logout_path, method: :delete, class: "text-gray-900 hover:underline py-2 rounded-md text-md font-medium", data: { confirm: "Are you sure?" } %>
            <% else %>
              <%= link_to 'Login', login_path, class: "text-gray-900 hover:underline py-2 rounded-md text-md font-medium" %>
            <% end %>
          </div>
        </div>
        <div class="hidden sm:flex items-center justify-center">
          <div class="flex space-x-10">
              <%= link_to "Home", root_path, class: "text-gray-900 hover:underline py-2 rounded-md text-md font-medium" %>
          </div>
        </div>
        <div class="flex-shrink-0 flex items-center">
          <%= link_to root_path do %>
            <%= image_tag 'logo.png', class: 'block lg:hidden h-20 w-auto' %>
          <% end %>
          <%= link_to root_path do %>
            <%= image_tag 'logo.png', class: 'hidden lg:block h-20 w-auto' %>
          <% end %>
        </div>
         <div class="hidden sm:flex sml:ml-6 items-center justify-center">
          <div class="flex space-x-10">
              <%= link_to "Hotels", hotels_path, class: "text-gray-900 hover:underline py-2 rounded-md text-md font-medium" %>
          </div>
        </div>
        <div class="hidden sm:flex sml:ml-6 items-center justify-center">
          <div class="flex space-x-10">
             <% if logged_in? %>
              <%= link_to "My Bookings", bookings_path, class: "text-gray-900 hover:underline py-2 rounded-md text-md font-medium" %>
            <% else %>
              <%= link_to 'Sign up', signup_path, class: "text-gray-900 hover:underline py-2 rounded-md text-md font-medium" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</nav>