config/routes.rb
Rails.application.routes.draw do
  get "password_resets/new"
  get "password_resets/edit"
  namespace :admin do
      resources :hotels
      resources :day_price_adjustments
      resources :bookings do
        member do
          patch :toggle_status
        end
      end
      resources :users do
        member do
          patch :toggle_admin
        end
      end
  end

  resources :bookings do
    collection do
      post :calculate_price
    end
    member do
      patch :cancel
    end
  end
  resources :hotels do
    member do
      post :room_price
    end
    resources :reviews
  end
  resources :users, only: [ :show, :edit, :update, :create ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "home#index"

  get "admin", to: "admin#index", as: "admin"

  get "signup" => "users#new"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  resources :account_activations, only: [ :edit ]
  resources :password_resets, only: [ :new, :create, :edit, :update ]
end

app/models/hotel.rb
class Hotel < ApplicationRecord
    has_many_attached :images
    has_many :bookings, dependent: :destroy
    has_many :reviews, dependent: :destroy

    validates :name, presence: true, length: { maximum: 50 }
    validates :description, presence: true
    VALID_MOBILE_REGEX = /\A(08|09)[0-9]{9}\z/
    validates :contact_details, presence: true, format: { with: VALID_MOBILE_REGEX, message: "must be a valid Philippine mobile number starting with 0" }
    validates :single_room_price, :double_room_price, :suite_price, presence: true
    validate :room_price_order
    validate :positive_room_prices

    private

    def room_price_order
      if single_room_price.present? && double_room_price.present? && suite_price.present?
        if single_room_price >= double_room_price
          errors.add(:single_room_price, "must be less than double room price")
        end

        if double_room_price >= suite_price
          errors.add(:double_room_price, "must be less than suite price")
        end

        if single_room_price >= suite_price
          errors.add(:single_room_price, "must be less than suite price")
        end
      end
    end

    def positive_room_prices
      if single_room_price.present? && double_room_price.present? && suite_price.present?
      if single_room_price <= 0
        errors.add(:single_room_price, "must be greater than 0")
      end

      if double_room_price <= 0
        errors.add(:double_room_price, "must be greater than 0")
      end

      if suite_price <= 0
        errors.add(:suite_price, "must be greater than 0")
      end
      end
  end
end

app/controllers/admin/hotels_controller.rb
class Admin::HotelsController < AdminController
  before_action :admin_hotel_params
  before_action :set_admin_hotel, only: [ :show, :edit, :update, :destroy ]

  def index
    @admin_hotels = Hotel.all

    # Apply search filter if search params are present
    if params[:search].present?
      search_term = params[:search].downcase
      @admin_hotels = @admin_hotels.where("LOWER(name) LIKE :search OR LOWER(location) LIKE :search", search: "%#{search_term}%")
    end

    if params[:id].present?
      @admin_hotels = Hotel.where(id: params[:id])
    end

    # Sort hotels by name ascending or descending based on params[:order]
    if params[:order] == "name_asc"
      @admin_hotels = @admin_hotels.order(name: :asc)
    elsif params[:order] == "name_desc"
      @admin_hotels = @admin_hotels.order(name: :desc)
    elsif params[:order] == "id_asc"
      @admin_hotels = @admin_hotels.order(id: :asc)
    elsif params[:order] == "id_desc"
      @admin_hotels = @admin_hotels.order(id: :desc)
    else
      @admin_hotels = @admin_hotels.order(id: :asc)
    end

    @admin_hotels = @admin_hotels.paginate(page: params[:page], per_page: 10)
  end



  def show
  end

  def new
    @admin_hotel = Hotel.new
  end

  def create
    @admin_hotel = Hotel.new(admin_hotel_params)
    @admin_hotel.amenities = params[:hotel][:amenities].join(",") if params[:hotel][:amenities].present?

    # Logging parameters
    Rails.logger.info "Parameters submitted for create action: #{admin_hotel_params.inspect}"

    respond_to do |format|
      if @admin_hotel.save
        if params[:hotel][:images].present?
          @admin_hotel.images.attach(params[:hotel][:images])
        end
        format.html { redirect_to admin_hotel_url(@admin_hotel) }
        format.json { render :show, status: :created, location: @admin_hotel }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @admin_hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    Rails.logger.info "Parameters submitted for update action: #{admin_hotel_params.inspect}"

    respond_to do |format|
      if @admin_hotel.update(admin_hotel_params.except(:images, :delete_images))
        # Handle image attachments
        if params[:hotel][:images].present?
          params[:hotel][:images].each do |image|
            @admin_hotel.images.attach(image)
          end
        end


      if params[:hotel][:delete_images].present?
        params[:hotel][:delete_images].each do |image_id|
          image = @admin_hotel.images.find_by_id(image_id)
          if image
            image.purge
            image.blob.purge
            Rails.logger.info "Deleted image #{image_id} from S3."
          else
            Rails.logger.warn "Image #{image_id} not found."
          end
        end
      end

        if params[:hotel][:amenities].present?
          @admin_hotel.amenities = params[:hotel][:amenities].join(",")
          @admin_hotel.save
        end

        format.html { redirect_to admin_hotel_url(@admin_hotel), notice: "Hotel was successfully updated." }
        format.json { render :show, status: :ok, location: @admin_hotel }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @admin_hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @admin_hotel.destroy!

    respond_to do |format|
      format.html { redirect_to admin_hotels_url, notice: "Hotel was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private

  def set_admin_hotel
    @admin_hotel = Hotel.find(params[:id])
  end

  def admin_hotel_params
    params.permit(
      :id, :search, :order, :page,
      :name, :description, :location, :contact_details,
      :single_room_price, :double_room_price, :suite_price,
      images: [],
      delete_images: [],
      amenities: []
    )
  end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  # GET /hotels or /hotels.json
  def index
    @hotels = Hotel.all
    if params[:location].present?
      @hotels = @hotels.where("location ILIKE ?", "%#{params[:location]}%")
    end
    if params[:start_date].present? && params[:end_date].present? && params[:room_type].present?
      start_date = Date.parse(params[:start_date])
      end_date = Date.parse(params[:end_date])
      room_type = params[:room_type]

      # Filter hotels that do not have any overlapping bookings for the specified room type and date range
      @hotels = @hotels.where.not(id: Hotel.joins(:bookings).where("bookings.room_type = ? AND bookings.start_date <= ? AND bookings.end_date >= ?", room_type, end_date, start_date)).distinct
    else
      flash.now[:alert] = "Please provide start date, end date, and room type for the search." if params[:start_date].present? || params[:end_date].present?
    end
    @hotels = @hotels.paginate(page: params[:page], per_page: 9)
  end

  # GET /hotels/1 or /hotels/1.json
  def show
    @current_user = current_user
    @hotel = Hotel.find(params[:id])
  end

  def room_price
    hotel = Hotel.find(params[:id])
    room_type = params[:room_type]
    room_price = PricingHelper.room_price_for_type(hotel, room_type)

    render json: { room_price: room_price }
  rescue => e
    render json: { error: e.message }, status: :unprocessable_entity
  end

  private

    # Only allow a list of trusted parameters through.
    def hotel_params
      params.require(:hotel).permit(:id, :name, :description, :location, :contact_details, :amenities, :single_room_price, :double_room_price, :suite_price)
    end
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/views/admin/hotels/_form.html.erb
<%= form_with(model: [:admin, @admin_hotel], class: "contents", multipart: true) do |form| %>

  <% if @admin_hotel.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(@admin_hotel.errors.count, "error") %> prohibited this admin_hotel from being saved:</h2>

      <ul>
        <% @admin_hotel.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :location %>
    <%= form.text_field :location, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :contact_details %>
    <%= form.text_field :contact_details, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
  <%= form.label :amenities %>
  <% selected_amenities = @admin_hotel.amenities.present? ? @admin_hotel.amenities.split(',').map(&:strip) : [] %>
  <% ['Pool', 'Gym', 'Spa', 'Restaurant', 'WiFi', 'Parking', 'Pet-friendly'].each do |amenity| %>
    <label class="block mt-2">
      <%= check_box_tag 'hotel[amenities][]', amenity, selected_amenities.include?(amenity), class: "mr-2 leading-tight" %>
      <%= amenity %>
    </label>
  <% end %>
</div>



  <div class="my-5 flex justify-between">
    <div class="w-1/4">
      <%= form.label :single_room_price, class: "block mb-1" %>
      <%= form.number_field :single_room_price, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 w-full", min: 1 %>
    </div>
    <div class="w-1/4">
      <%= form.label :double_room_price, class: "block mb-1" %>
      <%= form.number_field :double_room_price, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 w-full", min: 1 %>
    </div>
    <div class="w-1/4">
      <%= form.label :suite_price, class: "block mb-1" %>
      <%= form.number_field :suite_price, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 w-full", min: 1 %>
    </div>
  </div>

  <div class="my-5">
    <%= form.label :images, "Upload Images" %>
    <%= form.file_field :images, multiple: true, class: "block mt-2", accept: 'image/*' %>
  </div>

  <% if local_assigns[:show_photos] && @admin_hotel.images.present? %>
    <div class="my-5">
      <h2>Delete Photos:</h2>

      <div class="flex flex-wrap gap-4">
        <% @admin_hotel.images.each do |image| %>
          <div class="col-md-3 mb-3">
            <%= image_tag url_for(image.variant(resize: "100x100")), class: "preview-image" %>
            <%= form.check_box :delete_images, { multiple: true }, image.id, nil %>
          </div>
        <% end %>
      </div>

    </div>
  <% end %>




  

  <div class="flex justify-between mt-4 my-5">
    <%= link_to "Back to hotels", admin_hotels_path, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="flex ml-4">
      <% if local_assigns[:show_photos]%>
    <%= link_to "Show this hotel", [:admin, @admin_hotel], class: "mr-2 rounded-lg py-3 px-5 inline-block font-medium", style: "background-color: #3b606f; color: #e4ebe8;" %>
    <% end %>
    <%= form.submit class: "rounded-lg py-3 px-5 font-medium cursor-pointer", style: "background-color: #e4ebe8; color: #3b606f;" %>
    </div>
  </div>
<% end %>

app/views/admin/hotels/_hotel.html.erb
<div id="<%= dom_id hotel %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= hotel.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= hotel.description %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Location:</strong>
    <%= hotel.location %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Contact details:</strong>
    <%= hotel.contact_details %>
  </p>

  <p class="my-3">
    <strong class="block font-medium mb-1">Amenities:</strong>
      <% if hotel.amenities.present? %>
        <% hotel.amenities.split(',').each do |amenity| %>
          <li><%= amenity.strip %></li>
        <% end %>
      <% else %>
        <p>No amenities listed.</p>
      <% end %>
  </p>
  
  <% if action_name != "show" %>
    <%= link_to "Show this hotel", [:admin, hotel], class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this hotel", edit_admin_hotel_path(hotel), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>

</div>

app/views/admin/hotels/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing hotel</h1>

  <%= render "form", hotel: @admin_hotel, show_photos: true %>
  
  
</div>

app/views/admin/hotels/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Hotels</h1>
  <div class="flex justify-between items-center">
  
  <div class="flex justify-between mb-4 mt-4">
  <%= form_with(url: admin_hotels_path, method: "get", local: true, class: "flex gap-4") do |form| %>
      <div>
      <%= form.label :id, "ID", class: "block text-sm font-medium text-gray-700" %>
      <%= form.number_field :id, value: params[:id], class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm", id: "search-id", min: 1 %>
      </div>
      <div>
      <%= form.label :search, "Name or Location", class: "block text-sm font-medium text-gray-700" %>
      <%= form.text_field :search, value: params[:search], class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm", id: "search-input" %>
      </div>
      <div class="flex items-end gap-1">
       <%= form.submit "Filter", class: "inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm hover:sky-100 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500 cursor-pointer", style: "background-color: #3b606f; color: #e4ebe8;" %>
            <% if params[:id].present? || params[:search].present? %>
              <%= link_to "Clear", admin_hotels_path, class: "inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500 cursor-pointer", style: "background-color: #e4ebe8; color: #3b606f;" %>
            <% end %>
          </div>
  <% end %>
  </div>
  <%= link_to "New hotel", new_admin_hotel_path, class: "rounded-lg py-3 px-5 block font-medium", style: "background-color: #3b606f; color: #e4ebe8;" %>
</div>


  

  <div class="flex flex-col w-full overlow-x-auto sm:mx-0.5 lg:mx-0.5">
    <div class="py-2 inline-block min-w-full">
      <div class="overlow-x-auto">
        <table class="min-w-full table-fixed overflow-x-scroll">
          <thead class="bg-white border-b">
            <tr>
              <th scope="col" class="w-1/6 text-sm font-medium text-gray-800 px-6 py-4 text-left">
                  <%= link_to url_for(params.permit(:page).merge(order: params[:order] == 'id_asc' || params[:order].blank? ? 'id_desc' : 'id_asc')), class: "flex items-center justify-between" do %>
                  <span>ID</span>
                  <% if params[:order] == 'id_asc' || params[:order].blank? %>
                    <i class="fas fa-arrow-down text-sm text-gray-500"></i>
                  <% else %>
                    <i class="fas fa-arrow-up text-sm text-gray-500"></i>
                  <% end %>
                  <% end %>
              </th>
              <th scope="col" class="w-1/4 text-sm font-medium text-gray-800 px-6 py-4 text-left">
                  <%= link_to url_for(params.permit(:page).merge(order: params[:order] == 'name_asc' || params[:order].blank? ? 'name_desc' : 'name_asc')), class: "flex items-center justify-between" do %>
                  <span>Name</span>
                  <% if params[:order] == 'name_asc' || params[:order].blank? %>
                    <i class="fas fa-arrow-down text-sm text-gray-500"></i>
                  <% else %>
                    <i class="fas fa-arrow-up text-sm text-gray-500"></i>
                  <% end %>
                  <% end %>
              </th>
              <th scope="col" class="w-1/2 text-sm font-medium text-gray-800 px-6 py-4 text-left">Location</th>
              <th scope="col" class="w-1/8 text-sm font-medium text-gray-800 px-6 py-4 text-left">Actions</th>
            </tr>
          </thead>
          <tbody>
            <% @admin_hotels.each do |hotel| %>
            <tr class="bg-gray-50 border-b cursor-pointer" data-url="<%= admin_hotel_path(hotel) %>">
              <td class="px-6 py-4 text-sm font-medium text-gray-800"><%= hotel.id %></td>
              <td class="px-6 py-4 text-sm font-medium text-gray-800"><%= hotel.name %></td>
              <td class="px-6 py-4 text-sm font-medium text-gray-800"><%= hotel.location %></td>
              <td class="px-6 py-4 text-sm font-medium text-gray-800 relative">
                <div class="flex justify-center items-center">
                  <div class= "flex flex-col">
                  <button class="rounded-full focus:outline-none focus:ring-0 focus:ring-blue-500 flex items-center mt-2" id="options-menu-<%= hotel.id %>" aria-haspopup="true" aria-expanded="false">
                    <svg class="h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                      <path fill-rule="evenodd" d="M10 6a2 2 0 100-4 2 2 0 000 4zM2 6a2 2 0 100-4 2 2 0 000 4zm16 0a2 2 0 100-4 2 2 0 000 4z" clip-rule="evenodd" />
                    </svg>
                  </button>

                  <div class="absolute bg-white rounded-lg shadow-lg ring-1 ring-black ring-opacity-5 hidden mt-8 left-4 z-10">
                    <%= link_to "Edit", edit_admin_hotel_path(hotel), class: "block text-center px-4 py-2 text-sm text-gray-700 hover:bg-gray-100", role: "menuitem", data: { turbolinks: false } %>
                    <%= button_to "Delete", admin_hotel_path(hotel), method: :delete, data: { confirm: "Are you sure you want to delete this hotel?" }, class: "block w-full text-center px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 mt-1", role: "menuitem", data: { turbolinks: false } %>
                  </div>
                  </div>
                </div>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
    
  </div>
</div>

<div class="pagination flex justify-end mt-4">
      <% if @admin_hotels.total_pages > 1 %>
    <ul class="flex items-center">
      <% if @admin_hotels.current_page > 1 %>
        <li><%= link_to "« Previous", url_for(params.permit!.merge(page: @admin_hotels.current_page - 1)), class: "px-3 py-1 bg-gray-200 text-gray-700 rounded-md mr-2" %></li>
      <% else %>
        <li><span class="px-3 py-1 bg-gray-200 text-gray-400 rounded-md mr-2">« Previous</span></li>
      <% end %>

      <% @admin_hotels.total_pages.times do |page| %>
        <% if @admin_hotels.current_page == page + 1 %>
          <li><span class="px-3 py-1 rounded-md mr-2" style="background-color: #3b606f; color: #e4ebe8;"><%= page + 1 %></span></li>
        <% else %>
          <li><%= link_to page + 1, url_for(params.permit!.merge(page: page + 1)), class: "px-3 py-1 bg-gray-200 text-gray-700 rounded-md mr-2" %></li>
        <% end %>
      <% end %>

      <% if @admin_hotels.current_page < @admin_hotels.total_pages %>
        <li><%= link_to "Next »", url_for(params.permit!.merge(page: @admin_hotels.current_page + 1)), class: "px-3 py-1 bg-gray-200 text-gray-700 rounded-md ml-2" %></li>
      <% else %>
        <li><span class="px-3 py-1 bg-gray-200 text-gray-400 rounded-md ml-2">Next »</span></li>
      <% end %>
    </ul>
  <% end %>
    </div>


<script>
document.addEventListener("DOMContentLoaded", function() {
  const rows = document.querySelectorAll("tr[data-url]");
  const buttons = document.querySelectorAll("[id^='options-menu-']");

  buttons.forEach(button => {
    button.addEventListener("click", function(event) {
      event.stopPropagation(); // Prevents the click event from reaching the row
      const menu = this.nextElementSibling;
      menu.classList.toggle("hidden");
    });
  });

  rows.forEach(row => {
    row.addEventListener("click", function() {
      window.location.href = this.dataset.url;
    });
  });
});

</script>

app/views/admin/hotels/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New hotel</h1>

  <%= render "form", hotel: @admin_hotel %>

</div>

app/views/admin/hotels/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @admin_hotel %>

    <div class="my-5">
      <strong class="block font-medium mb-1">Current Photos:</strong>
      
      <% if @admin_hotel.images.any? %>
        <div class="flex flex-wrap gap-4">
          <% @admin_hotel.images.each do |image| %>
            <%= image_tag image.variant(resize: "300x300"), class: "rounded-md border border-gray-300 shadow" %>
          <% end %>
        </div>
      <% else %>
        <p>No photos yet.</p>
      <% end %>
    </div>

    
    <div class="flex justify-between mt-4 my-5">
      <%= link_to "Back to hotels", admin_hotels_path, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      
      <div class="flex ml-4">
        <%= link_to "Edit this hotel", edit_admin_hotel_path(@admin_hotel), class: "mr-2 rounded-lg py-3 px-5 inline-block font-medium", style: "background-color: #3b606f; color: #e4ebe8;" %>

        <%= button_to "Delete this hotel", admin_hotel_path(@admin_hotel), method: :delete, class: "rounded-lg py-3 px-5 font-medium", style: "background-color: #e4ebe8; color: #3b606f;" %>

      </div>
    </div>
  </div>
</div>