config/routes.rb
Rails.application.routes.draw do
  get "password_resets/new"
  get "password_resets/edit"
  namespace :admin do
      resources :hotels
      resources :day_price_adjustments
      resources :bookings do
        member do
          patch :toggle_status
        end
      end
      resources :users do
        member do
          patch :toggle_admin
        end
      end
  end

  resources :bookings do
    collection do
      post :calculate_price
    end
    member do
      patch :cancel
    end
  end
  resources :hotels do
    member do
      post :room_price
    end
    resources :reviews
  end
  resources :users, only: [ :show, :edit, :update, :create ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "home#index"

  get "admin", to: "admin#index", as: "admin"

  get "signup" => "users#new"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  resources :account_activations, only: [ :edit ]
  resources :password_resets, only: [ :new, :create, :edit, :update ]
end

app/models/hotel.rb
class Hotel < ApplicationRecord
    has_many_attached :images
    has_many :bookings, dependent: :destroy
    has_many :reviews, dependent: :destroy

    validates :name, presence: true, length: { maximum: 50 }
    validates :description, presence: true
    VALID_MOBILE_REGEX = /\A(08|09)[0-9]{9}\z/
    validates :contact_details, presence: true, format: { with: VALID_MOBILE_REGEX, message: "must be a valid Philippine mobile number starting with 0" }
    validates :single_room_price, :double_room_price, :suite_price, presence: true
    validate :room_price_order
    validate :positive_room_prices

    private

    def room_price_order
      if single_room_price.present? && double_room_price.present? && suite_price.present?
        if single_room_price >= double_room_price
          errors.add(:single_room_price, "must be less than double room price")
        end

        if double_room_price >= suite_price
          errors.add(:double_room_price, "must be less than suite price")
        end

        if single_room_price >= suite_price
          errors.add(:single_room_price, "must be less than suite price")
        end
      end
    end

    def positive_room_prices
      if single_room_price.present? && double_room_price.present? && suite_price.present?
      if single_room_price <= 0
        errors.add(:single_room_price, "must be greater than 0")
      end

      if double_room_price <= 0
        errors.add(:double_room_price, "must be greater than 0")
      end

      if suite_price <= 0
        errors.add(:suite_price, "must be greater than 0")
      end
      end
  end
end

app/controllers/admin/hotels_controller.rb
class Admin::HotelsController < AdminController
  before_action :admin_hotel_params
  before_action :set_admin_hotel, only: [ :show, :edit, :update, :destroy ]

  def index
    @admin_hotels = Hotel.all

    # Apply search filter if search params are present
    if params[:search].present?
      search_term = params[:search].downcase
      @admin_hotels = @admin_hotels.where("LOWER(name) LIKE :search OR LOWER(location) LIKE :search", search: "%#{search_term}%")
    end

    if params[:id].present?
      @admin_hotels = Hotel.where(id: params[:id])
    end

    # Sort hotels by name ascending or descending based on params[:order]
    if params[:order] == "name_asc"
      @admin_hotels = @admin_hotels.order(name: :asc)
    elsif params[:order] == "name_desc"
      @admin_hotels = @admin_hotels.order(name: :desc)
    elsif params[:order] == "id_asc"
      @admin_hotels = @admin_hotels.order(id: :asc)
    elsif params[:order] == "id_desc"
      @admin_hotels = @admin_hotels.order(id: :desc)
    else
      @admin_hotels = @admin_hotels.order(id: :asc)
    end

    @admin_hotels = @admin_hotels.paginate(page: params[:page], per_page: 10)
  end



  def show
  end

  def new
    @admin_hotel = Hotel.new
  end

  def create
    @admin_hotel = Hotel.new(admin_hotel_params)
    @admin_hotel.amenities = params[:hotel][:amenities].join(",") if params[:hotel][:amenities].present?

    # Logging parameters
    Rails.logger.info "Parameters submitted for create action: #{admin_hotel_params.inspect}"

    respond_to do |format|
      if @admin_hotel.save
        if params[:hotel][:images].present?
          @admin_hotel.images.attach(params[:hotel][:images])
        end
        format.html { redirect_to admin_hotel_url(@admin_hotel) }
        format.json { render :show, status: :created, location: @admin_hotel }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @admin_hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    Rails.logger.info "Parameters submitted for update action: #{admin_hotel_params.inspect}"

    respond_to do |format|
      if @admin_hotel.update(admin_hotel_params.except(:images, :delete_images))
        # Handle image attachments
        if params[:hotel][:images].present?
          params[:hotel][:images].each do |image|
            @admin_hotel.images.attach(image)
          end
        end


      if params[:hotel][:delete_images].present?
        params[:hotel][:delete_images].each do |image_id|
          image = @admin_hotel.images.find_by_id(image_id)
          if image
            image.purge
            image.blob.purge
            Rails.logger.info "Deleted image #{image_id} from S3."
          else
            Rails.logger.warn "Image #{image_id} not found."
          end
        end
      end

        if params[:hotel][:amenities].present?
          @admin_hotel.amenities = params[:hotel][:amenities].join(",")
          @admin_hotel.save
        end

        format.html { redirect_to admin_hotel_url(@admin_hotel), notice: "Hotel was successfully updated." }
        format.json { render :show, status: :ok, location: @admin_hotel }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @admin_hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @admin_hotel.destroy!

    respond_to do |format|
      format.html { redirect_to admin_hotels_url, notice: "Hotel was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private

  def set_admin_hotel
    @admin_hotel = Hotel.find(params[:id])
  end

  def admin_hotel_params
    params.permit(
      :id, :search, :order, :page,
      :name, :description, :location, :contact_details,
      :single_room_price, :double_room_price, :suite_price,
      images: [],
      delete_images: [],
      amenities: []
    )
  end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  # GET /hotels or /hotels.json
  def index
    @hotels = Hotel.all
    if params[:location].present?
      @hotels = @hotels.where("location ILIKE ?", "%#{params[:location]}%")
    end
    if params[:start_date].present? && params[:end_date].present? && params[:room_type].present?
      start_date = Date.parse(params[:start_date])
      end_date = Date.parse(params[:end_date])
      room_type = params[:room_type]

      # Filter hotels that do not have any overlapping bookings for the specified room type and date range
      @hotels = @hotels.where.not(id: Hotel.joins(:bookings).where("bookings.room_type = ? AND bookings.start_date <= ? AND bookings.end_date >= ?", room_type, end_date, start_date)).distinct
    else
      flash.now[:alert] = "Please provide start date, end date, and room type for the search." if params[:start_date].present? || params[:end_date].present?
    end
    @hotels = @hotels.paginate(page: params[:page], per_page: 9)
  end

  # GET /hotels/1 or /hotels/1.json
  def show
    @current_user = current_user
    @hotel = Hotel.find(params[:id])
  end

  def room_price
    hotel = Hotel.find(params[:id])
    room_type = params[:room_type]
    room_price = PricingHelper.room_price_for_type(hotel, room_type)

    render json: { room_price: room_price }
  rescue => e
    render json: { error: e.message }, status: :unprocessable_entity
  end

  private

    # Only allow a list of trusted parameters through.
    def hotel_params
      params.require(:hotel).permit(:id, :name, :description, :location, :contact_details, :amenities, :single_room_price, :double_room_price, :suite_price)
    end
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/views/hotels/index.html.erb
<div class="container mx-auto px-6 mt-8 mb-8">
  <h1 class="text-3xl font-bold mb-4 text-white">Hotels</h1>

  <% if logged_in? %>
  <div class="mb-4">
    <%= form_with(url: hotels_path, method: :get, local: true, class: "flex gap-4") do |form| %>
      <div>
        <%= form.label :location, "Location", class: "block text-sm font-medium text-white" %>
        <%= form.text_field :location, value: params[:location], class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm" %>
      </div>
      <div>
        <%= form.label :start_date, "Start Date", class: "block text-sm font-medium text-white" %>
        <%= form.date_field :start_date, value: params[:start_date], class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm" %>
      </div>
      <div>
        <%= form.label :end_date, "End Date", class: "block text-sm font-medium text-white" %>
        <%= form.date_field :end_date, value: params[:end_date], class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm" %>
      </div>
      <div>
        <%= form.label :room_type, "Room Type", class: "block text-sm font-medium text-white" %>
        <%= form.select :room_type, options_for_select([["Single Room", "single_room"], ["Double Room", "double_room"], ["Suite", "suite"]], params[:room_type]), class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm" %>
      </div>
      <div class="flex items-end gap-1">
        <%= form.submit "Search", class: "inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500" %>
        <% if params[:location].present? || params[:start_date].present? || params[:end_date].present? || params[:room_type].present? %>
          <%= link_to "Clear", hotels_path, class: "inline-flex items-center px-4 py-2 border border-gray-300 text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500" %>
        <% end %>
      </div>
    <% end %>
  </div>
  <% end %>

  <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
    <% @hotels.each do |hotel| %>
      <div class="bg-white shadow-md rounded-lg overflow-hidden">
        <% if hotel.images.attached? %>
            <%= image_tag hotel.images.first.variant(resize: "400x300"), class: "w-full h-64 object-cover object-center" %>
        <% else %>
            <%= image_tag "logo.png", class: "w-full h-64 object-cover object-center" %>
        <% end %>
        <div class="p-4">
          <h2 class="text-xl font-bold mb-2"><%= hotel.name %></h2>
          <p class="text-gray-600 mb-2"><%= hotel.location %></p>
          <p class="text-gray-700 mb-4"><%= truncate(hotel.description, length: 150) %></p>
          <div class="flex justify-between items-center">
            <div>
              <%= link_to "View Details", hotel_path(hotel), class: "bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded" %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    <div class="pagination flex justify-end mt-4">
      <% if @hotels.total_pages > 1 %>
        <ul class="flex items-center">
          <% if @hotels.current_page > 1 %>
            <li><%= link_to "« Previous", url_for(params.permit!.merge(page: @hotels.current_page - 1)), class: "px-3 py-1 bg-gray-200 text-gray-700 rounded-md mr-2" %></li>
          <% else %>
            <li><span class="px-3 py-1 bg-gray-200 text-gray-400 rounded-md mr-2">« Previous</span></li>
          <% end %>

          <% @hotels.total_pages.times do |page| %>
            <% if @hotels.current_page == page + 1 %>
              <li><span class="px-3 py-1 bg-blue-600 text-white rounded-md mr-2"><%= page + 1 %></span></li>
            <% else %>
              <li><%= link_to page + 1, url_for(params.permit!.merge(page: page + 1)), class: "px-3 py-1 bg-gray-200 text-gray-700 rounded-md mr-2" %></li>
            <% end %>
          <% end %>

          <% if @hotels.current_page < @hotels.total_pages %>
            <li><%= link_to "Next »", url_for(params.permit!.merge(page: @hotels.current_page + 1)), class: "px-3 py-1 bg-gray-200 text-gray-700 rounded-md ml-2" %></li>
          <% else %>
            <li><span class="px-3 py-1 bg-gray-200 text-gray-400 rounded-md ml-2">Next »</span></li>
          <% end %>
        </ul>
      <% end %>
    </div>
  </div>
</div>

app/views/hotels/show.html.erb
<div class="container mx-auto px-4 sm:px-6 lg:px-8 mt-8 mb-8">
  <div class="bg-white shadow-md rounded-lg overflow-hidden">
    <div class="p-6">

      <h2 class="text-3xl font-bold mb-2"><%= @hotel.name %></h2>
      <p class="text-gray-600 mb-4"><%= @hotel.location %></p>
      <p class="text-gray-700 mb-6"><%= @hotel.description %></p>
      
      <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
        
        <div class="col-span-1">
          <h3 class="text-lg font-semibold mb-2">Room Prices</h3>
          <div class="text-gray-700">
            <p>Single Room: $<%= @hotel.single_room_price %></p>
            <p>Double Room: $<%= @hotel.double_room_price %></p>
            <p>Suite: $<%= @hotel.suite_price %></p>
          </div>
        </div>

        <% if @hotel.amenities.present? %>
          <div class="col-span-1">
            <h3 class="text-lg font-semibold mb-2">Amenities</h3>
            <ul class="text-gray-700">
              <% @hotel.amenities.split(',').each do |amenity| %>
                <li><%= amenity.strip %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="col-span-1">
          <h3 class="text-lg font-semibold mb-2">Contact Details</h3>
          <ul class="text-gray-700">
            <li><%= @hotel.contact_details %></li>
          </ul>
        </div>

      </div>

      <div class="my-5">
        <h3 class="text-lg font-semibold mb-2">Photo Gallery</h3>
        
        <% if @hotel.images.any? %>
          <div class="flex flex-wrap gap-4">
            <% @hotel.images.each do |image| %>
              <%= image_tag image.variant(resize: "300x300"), class: "rounded-md border border-gray-300 shadow" %>
            <% end %>
          </div>
        <% else %>    
          <p>No photos yet.</p>
        <% end %>
      </div>

      <div class="my-5">
  <h3 class="text-lg font-semibold mb-2">Reviews</h3>

  <% if @hotel.reviews.any? %>
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
      <% @hotel.reviews.each do |review| %>
        <div class="bg-gray-100 rounded-lg p-4">
          <p><%= review.content %></p>
          <div class="flex items-center mt-2">
            <span class="text-gray-600 mr-2">Rating:</span>
            <% review.rating.times do %>
              <svg class="h-5 w-5 text-yellow-500" fill="currentColor" viewBox="0 0 20 20">
                <path fill-rule="evenodd" d="M10 0l2.37 6.08 6.29.48c.83.06 1.18 1.13.56 1.69l-4.83 4.25 1.43 6.1c.19.81-.61 1.46-1.29 1.04L10 15.4l-5.04 3.13c-.68.42-1.48-.23-1.29-1.04l1.43-6.1-4.83-4.25c-.62-.55-.27-1.63.56-1.69l6.29-.48L10 0z" clip-rule="evenodd"/>
              </svg>
            <% end %>
          </div>
          <p class="text-gray-600 mt-1">By: <%= review.user.first_name %> <%= review.user.last_name %> | <%= time_ago_in_words(review.created_at) %> ago</p>
        </div>
      <% end %>
    </div>
  <% else %>
    <p>No reviews yet.</p>
  <% end %>
</div>


      <div class="flex justify-between items-center mt-6">
        <%= link_to "Back to Hotels", hotels_path, class: "text-blue-500 hover:underline" %>
        <div class="flex space-x-4">
           <% if logged_in? && current_user.bookings.exists?(hotel_id: @hotel.id) %>
            <%= link_to "Leave a Review", new_hotel_review_path(@hotel), class: "bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded" %>
          <% end %>
          <%= link_to "Book Now", new_booking_path(hotel_id: @hotel.id), class: "bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded" %>
        </div>
      </div>

    </div>
  </div>
</div>